[package]
name = "sqlite_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
reqwest = { version = "0.11", features = ["blocking"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "minigrep"
path = "src/main.rs"
